export const SITE = {
  name: "Ritik Kumar",
  role: "Software Engineer",
  roleAlt: "AI Developer",
  tagline: "Building intelligent applications with modern web technologies, AI, and cloud infrastructure.",
  email: "ritikkumar12bicbly@gmail.com",
  phone: "+919808470386",
  location: "Bareilly, Uttar Pradesh, India",
  resumeUrl: "",
  github: "https://github.com/R1T1KKUMAR",
  linkedin: "https://www.linkedin.com/in/ritik-kumar-ba7931293",
  socialLinks: [
    { id: "github", label: "GitHub", href: "https://github.com/R1T1KKUMAR" },
    { id: "linkedin", label: "LinkedIn", href: "https://www.linkedin.com/in/ritik-kumar-ba7931293" },
    { id: "email", label: "Email", href: "mailto:ritikkumar12bicbly@gmail.com" },
  ],
  education: {
    degree: "B.Tech in Computer Science",
    university: "Invertis University",
    location: "Bareilly",
    period: "2023 – 2027",
  },
  about: {
    bio: "I'm a software engineer and AI developer passionate about building intelligent, scalable applications. I combine modern web technologies with machine learning to create products that make a real impact.",
    focus: "Full-Stack Development & AI Integration",
    values: ["Clean Code", "Performance", "User Experience", "Continuous Learning"],
    location: "Bareilly, India",
  },
  experience: [
    {
      role: "Software Engineer Intern",
      company: "Tech Company",
      period: "Jan 2025 – Present",
      description: "Building full-stack applications with React, Node.js, and cloud services. Implementing AI-powered features and optimizing system performance.",
      highlights: [
        "Developed and deployed 3+ production applications",
        "Reduced API response times by 40%",
        "Implemented CI/CD pipelines",
      ],
    },
    {
      role: "Freelance Developer",
      company: "Self-Employed",
      period: "2023 – Present",
      description: "Building custom web applications, AI integrations, and automation solutions for clients across various industries.",
      highlights: [
        "Delivered 10+ client projects on time",
        "Built custom AI chatbots and automation tools",
        "Developed responsive, performant web applications",
      ],
    },
  ],
  skills: [
    { category: "Frontend", icon: "Code2", technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"] },
    { category: "Backend", icon: "Server", technologies: ["Node.js", "Express", "Python", "FastAPI", "REST APIs"] },
    { category: "AI & ML", icon: "Brain", technologies: ["TensorFlow", "PyTorch", "OpenAI", "LangChain", "Hugging Face"] },
    { category: "Cloud", icon: "Cloud", technologies: ["AWS", "Vercel", "Firebase", "Supabase", "Cloudflare"] },
    { category: "Databases", icon: "Database", technologies: ["PostgreSQL", "MongoDB", "Redis", "Prisma", "Drizzle"] },
    { category: "DevOps", icon: "Terminal", technologies: ["Docker", "GitHub Actions", "CI/CD", "Linux", "Nginx"] },
    { category: "Languages", icon: "Code", technologies: ["JavaScript", "TypeScript", "Python", "Java", "C++"] },
  ],
  projects: [
    {
      title: "AI-Powered Dashboard",
      description: "Intelligent analytics platform with real-time data visualization, predictive insights, and natural language querying.",
      image: "/projects/dashboard.jpg",
      tags: ["Next.js", "Python", "TensorFlow", "PostgreSQL"],
      liveUrl: "#",
      githubUrl: "https://github.com/R1T1KKUMAR",
      caseStudy: "#",
      problem: "Businesses struggled to derive actionable insights from their data due to complex analytics tools and lack of real-time processing.",
      solution: "Built an AI-powered dashboard that combines real-time data processing with natural language querying, enabling non-technical users to ask questions and get instant visual insights.",
      architecture: "Next.js frontend with WebSocket connections to a Python FastAPI backend. TensorFlow models for predictive analytics. PostgreSQL with TimescaleDB for time-series data.",
      techStack: ["Next.js", "TypeScript", "Python", "FastAPI", "TensorFlow", "PostgreSQL", "Redis", "Docker"],
      challenges: "Handling real-time data streams at scale while maintaining sub-100ms query response times for the NLP interface.",
      metrics: ["40% faster decision-making", "10K+ queries processed daily", "99.9% uptime"],
    },
    {
      title: "Smart Automation Platform",
      description: "Workflow automation platform with AI-driven task scheduling, intelligent routing, and real-time monitoring.",
      image: "/projects/automation.jpg",
      tags: ["React", "Node.js", "AWS", "MongoDB"],
      liveUrl: "#",
      githubUrl: "https://github.com/R1T1KKUMAR",
      caseStudy: "#",
      problem: "Teams spent 30% of their time on repetitive manual tasks, leading to burnout and reduced productivity.",
      solution: "Created an intelligent automation platform that learns from user behavior and suggests optimal workflows, automating routine tasks with smart scheduling.",
      architecture: "Microservices architecture with React frontend, Node.js backend, and AWS Lambda for serverless task execution. MongoDB for flexible workflow storage.",
      techStack: ["React", "Node.js", "AWS Lambda", "MongoDB", "Redis", "Docker", "GitHub Actions"],
      challenges: "Designing a workflow engine that could handle complex multi-step automations while remaining user-friendly for non-technical users.",
      metrics: ["30% time saved per employee", "5K+ automations created", "95% user satisfaction"],
    },
  ],
  achievements: [
    { title: "Built 10+ Production Apps", description: "Developed and deployed applications serving real users", icon: "Award" },
    { title: "Open Source Contributor", description: "Active contributor to multiple open-source projects", icon: "GitFork" },
    { title: "Hackathon Winner", description: "First place at university-level hackathon", icon: "Trophy" },
    { title: "100+ GitHub Contributions", description: "Consistent contributions to open-source and personal projects", icon: "GitCommit" },
  ],
  techStack: [
    { name: "React", category: "Frontend" },
    { name: "Next.js", category: "Frontend" },
    { name: "TypeScript", category: "Language" },
    { name: "Python", category: "Language" },
    { name: "Node.js", category: "Backend" },
    { name: "PostgreSQL", category: "Database" },
    { name: "MongoDB", category: "Database" },
    { name: "Docker", category: "DevOps" },
    { name: "AWS", category: "Cloud" },
    { name: "TensorFlow", category: "AI" },
    { name: "PyTorch", category: "AI" },
    { name: "Redis", category: "Database" },
    { name: "Prisma", category: "Backend" },
    { name: "Tailwind CSS", category: "Frontend" },
    { name: "Framer Motion", category: "Frontend" },
    { name: "Git", category: "DevOps" },
  ],
  testimonials: [
    {
      name: "Client Name",
      role: "CTO, Company",
      content: "Exceptional engineering skills and attention to detail. Delivered beyond expectations.",
    },
    {
      name: "Client Name",
      role: "Founder, Startup",
      content: "One of the best developers I've worked with. Deep understanding of both frontend and AI.",
    },
  ],
};
